### ISSUE TITLE
System and User Scope for settings

### ISSUE THREAD

**Issue by BCleverly** [anlutro/laravel-settings#56] opened 2016-07-05 14:46 UTC
I've seen the extra coloumn example, but I'm not quite sure how i can work it into what I'm trying to do.

I want to use the package for system settings on a website, but i also want to have users settings in the same table/setup.

An example would be pricebands.
System default settings would be say
1, Value: 5 - Qty: 100
2, Value: 10 - Qty 200
3, Value: 20 - Qty 400
User settings would make this say:
1, Value: 5 - Qty: 100
2, Value: 7.5 - Qty 300
3, Value: 10 - Qty 600

Is this possible within this package or would we have to build something custom?

Many thanks

**Comment by anlutro** [comment] 2016-07-05 21:23
So you basically want a set of global settings that can be overridden on a per-user basis? Would you want any setting to be overridden or only specific ones? Regardless, the feature isn't there today, but it might be something that makes sense to add.

**Comment by BCleverly** [comment] 2016-07-06 08:08
Basically yes.
I think that should be configurable, maybe by a flag in the database table row/model. 
Would be nice to see this in the future and would set the package out from the rest. 
I'll have a look at the package and see if i can work it into the package and make a pull request. Would you be able to label this as a feature request?

**Comment by anlutro** [comment] 2016-07-06 08:37
If you'd like to help develop the feature that'd be awesome.

I think since this is a somewhat complex feature, I think creating an additional class that extends the DatabaseSettingStore would be a good idea to prevent subtle bugs from creeping in.

**Comment by BCleverly** [comment] 2016-07-06 20:09
I'll see what I can do, any questions etc I'll keep them in this issue thread.

**Comment by anlutro** [comment] 2017-10-14 22:43
Sorry for the super late notification but I'm going through my issues and this is a duplicate of https://github.com/anlutro/laravel-settings/issues/3. I'm still interested in having it implemented, but will not be doing it myself (I'll be happy to help out anyone who wants to give it a shot).

**Closed by anlutro** 2017-10-14 22:43 UTC
